version: '3.6'

services:

  algorithmic-trading-exploration:
    build: .
    image: flaviostutz/algorithmic-trading-exploration
    environment:
      - JUPYTER_TOKEN=abc123
    ports:
      - 8888:8888
    volumes: 
      - ./notebooks:/notebooks
    # command: sleep 99999
